DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS recovery_outcomes CASCADE;
DROP TABLE IF EXISTS recovery_actions CASCADE;
DROP TABLE IF EXISTS recovery_decisions CASCADE;
DROP TABLE IF EXISTS recovery_predictions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS merchants CASCADE;
